import data from "@/data/la-contours.json";

/**
 * Real elevation contours of central Los Angeles (Santa Monica Mountains to downtown),
 * generated by scripts/build-contours.mjs. Every fifth line shares a band; hovering a
 * project lights up its band.
 */
export function Contours({ className = "" }: { className?: string }) {
  return (
    <svg
      className={`contours pointer-events-none absolute inset-0 h-full w-full ${className}`}
      viewBox={`0 0 ${data.width} ${data.height}`}
      preserveAspectRatio="xMidYMid slice"
      aria-hidden="true"
      data-bbox={JSON.stringify(data.bbox)}
    >
      {data.levels.map((l, i) => (
        <path key={l.elevation} d={l.d} data-band={i % 5} />
      ))}
    </svg>
  );
}
